{
  try {
    try {
      app.create(TestOne.class);
      fail("Should have raised an org.neo4j.graphdb.NotInTransactionException");
    }
 catch (    org.neo4j.graphdb.NotInTransactionException e) {
    }
    try {
      app.create(TestOne.class);
      fail("Should have raised an org.neo4j.graphdb.NotInTransactionException");
    }
 catch (    org.neo4j.graphdb.NotInTransactionException e) {
    }
    AbstractNode node=null;
    try (final Tx tx=app.tx()){
      node=app.create(TestOne.class);
      tx.success();
    }
     assertTrue(node != null);
    assertTrue(node instanceof TestOne);
  }
 catch (  FrameworkException ex) {
    logger.log(Level.SEVERE,ex.toString());
    fail("Unexpected exception");
  }
}
